Repository Segs/Segs, pull requests merged in 2018-11, with the labels that each got.

#673 A bunch of scary bugs came trick-or-treating, sweets were applied.
  Components/serialization_types.h
  Projects/CoX/Common/GameData/CommonNetStructures.h
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/Runtime/Prefab.cpp
  Projects/CoX/Common/Runtime/Prefab.h
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  include/version.h
Labels: review

#677 Bin converter supports sequencer.bin files now.
  Projects/CoX/Common/GameData/seq_definitions.h
  Projects/CoX/Common/GameData/seq_serializers.cpp
  Projects/CoX/Utilities/BinConverter/binConverter.cpp
Labels: enhancement, review

#678 Tasks / LuaBot added to Lua
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/CMakeLists.txt
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CharacterData.cpp
  Projects/CoX/Common/GameData/CharacterData.h
  Projects/CoX/Common/GameData/Task.cpp
  Projects/CoX/Common/GameData/Task.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/Tasks.h
  Projects/CoX/Data/scripts/City_00_01/entities.lua
  Projects/CoX/Data/scripts/City_00_01/locations.lua
  Projects/CoX/Data/scripts/City_00_01/plaques.lua
  Projects/CoX/Data/scripts/City_01_01/entities.lua
  Projects/CoX/Data/scripts/City_01_01/locations.lua
  Projects/CoX/Data/scripts/City_01_01/plaques.lua
  Projects/CoX/Data/scripts/global.lua
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, lua-related

#679 Less asserts where error messages will work
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#682 Fix LOD problems caused by not applying geometry 'mods'
  Projects/CoX/Common/Runtime/Prefab.cpp
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Common/Runtime/SceneGraph.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.cpp
  Projects/CoX/Utilities/MapViewer/src/CohModelConverter.cpp
  Projects/CoX/Utilities/MapViewer/src/SideWindow.cpp
Labels: review

#684 Load sequencer data.
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/seq_definitions.h
  Projects/CoX/Common/GameData/seq_serializers.cpp
  Projects/CoX/Common/GameData/seq_serializers.h
  Projects/CoX/Utilities/BinConverter/binConverter.cpp
Labels: review

#680 Clues - Souvenirs - Random Temp powers in Lua
  Projects/CoX/CMakeLists.txt
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CharacterData.cpp
  Projects/CoX/Common/GameData/CharacterData.h
  Projects/CoX/Common/GameData/Clue.cpp
  Projects/CoX/Common/GameData/Clue.h
  Projects/CoX/Common/GameData/Entity.cpp
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/ClueList.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Data/scripts/City_00_01/entities.lua
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
  Projects/CoX/Data/scripts/global.lua
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
Labels: enhancement

#683 Incremental NPC Generator improvements
  Components/Logging.cpp
  Components/Logging.h
  Projects/CoX/CMakeLists.txt
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/Messages/Map/InfoMessageCmd.h
  Projects/CoX/Common/Messages/Map/MapEvents.h
  Projects/CoX/Data/scripts/City_00_01/locations.lua
  Projects/CoX/Data/scripts/City_00_01/missions.lua
  Projects/CoX/Data/scripts/City_00_01/plaques.lua
  Projects/CoX/Data/scripts/City_01_01/missions.lua
  Projects/CoX/Data/scripts/global.lua
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.h
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, review

#693 Fixed bug I introduced into LuaBot
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
Labels: bug, review

#694 Hotfix for Training and Title window LuaBot issues
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
Labels: bug, review

#658 Tailor
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Common/GameData/Character.cpp
  Projects/CoX/Common/GameData/Character.h
  Projects/CoX/Common/GameData/CharacterData.cpp
  Projects/CoX/Common/GameData/CharacterData.h
  Projects/CoX/Common/GameData/CharacterHelpers.cpp
  Projects/CoX/Common/GameData/CharacterHelpers.h
  Projects/CoX/Common/GameData/Costume.cpp
  Projects/CoX/Common/GameData/Costume.h
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/Powers.cpp
  Projects/CoX/Common/GameData/Powers.h
  Projects/CoX/Common/GameData/Team.cpp
  Projects/CoX/Common/GameData/Team.h
  Projects/CoX/Common/GameData/clientoptions_definitions.h
  Projects/CoX/Common/GameData/clientoptions_serializers.cpp
  Projects/CoX/Common/GameData/gui_definitions.h
  Projects/CoX/Common/GameData/gui_serializers.cpp
  Projects/CoX/Common/Messages/Game/GameEvents.cpp
  Projects/CoX/Common/Messages/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/MapEvents.h
  Projects/CoX/Common/Messages/Map/TailorOpen.h
  Projects/CoX/Common/Runtime/Prefab.cpp
  Projects/CoX/Common/Runtime/RuntimeData.cpp
  Projects/CoX/Data/mysql/segs_game_mysql_create.sql
  Projects/CoX/Data/pgsql/segs_game_postgres_create.sql
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Data/sqlite/segs_game_sqlite_create.sql
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/GameServer/GameServer.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapManager.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.h
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.h
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement, review

#696 Spawn correctly on zone change and stop asserts on Pelegrine Island
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug, review

#697 Hash all spawners and use them to spawn and mapxfer
  Components/serialization_common.h
  Projects/CoX/Common/GameData/Clue.cpp
  Projects/CoX/Common/GameData/scenegraph_serializers.cpp
  Projects/CoX/Common/GameData/scenegraph_serializers.h
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Common/Runtime/SceneGraph.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.h
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: bug, enhancement, review

#703 lua: Set scripting engine default enabled
  CMakeLists.txt
Labels: bug

#704 Resolve /bigobj error on appveyor
  CMakeLists.txt
Labels: bug, review

#705 Add RPC endpoints and reading from settings file.
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/AuthServer/AdminRPC.h
Labels: enhancement

#709 Add gotospawn and mapmove slash commands.
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#711 Make some doors work.
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.h
Labels: enhancement

#715 Fix jcon build under macOS and re-enable Travis builds
  .travis.yml
  3rd_party/jcon-cpp/src/CMakeLists.txt
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
Labels: bug, review
