Repository Segs/Segs, pull requests merged in 2018-05, with the labels that each got.

#389 Quick NPC logging and NPC Name fixes
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.h
Labels: review

#354 Issue #293 (Serializing m_current_attribs), #304 (Replacing slashCommand string parameters with const), #352 (Handling Compiler Warnings)
  Projects/CoX/Common/GameData/Colors.h
  Projects/CoX/Common/GameData/DataStorage.cpp
  Projects/CoX/Common/GameData/attrib_serializers.cpp
  Projects/CoX/Common/GameData/attrib_serializers.h
  Projects/CoX/Common/GameData/chardata_definitions.h
  Projects/CoX/Common/GameData/chardata_serializers.cpp
  Projects/CoX/Common/GameData/entitydata_serializers.cpp
  Projects/CoX/Common/GameData/gui_serializers.cpp
  Projects/CoX/Common/GameData/npc_definitions.h
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Common/NetStructures/Costume.cpp
  Projects/CoX/Common/NetStructures/Team.cpp
  Projects/CoX/Common/NetStructures/Team.h
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Servers/GameServer/GameEvents.cpp
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/EntityStorage.cpp
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/InputState.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapServerData.cpp
  Projects/CoX/Servers/MapServer/NetCommandManager.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.h
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: enhancement, review

#395 Fix Typos
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
Labels: review

#397 Remember to flush!
  Projects/CoX/Servers/AuthServer/main.cpp
Labels: bug, review

#398 Add 'null' client patch.
  Projects/CoX/Clients/Client_I0_Null/CMakeLists.txt
  Projects/CoX/Clients/Client_I0_Null/dll_core.cpp
  Projects/CoX/Clients/Client_I0_Null/patch_all_the_things.cpp
  Projects/CoX/Clients/Client_I0_Null/patch_all_the_things.h
  Projects/CoX/Utilities/MapViewer/src/CohModelConverter.cpp
Labels: review

#401 Server-sync is now disabled by default
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Data/scripts/motd.smlx
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: review

#400 SEGSAdmin config and logging functionality
  Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.h
  Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.h
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.h
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.ui
  Projects/CoX/Utilities/SEGSAdmin/icon_good.png
  Projects/CoX/Utilities/SEGSAdmin/icon_warning.png
  Projects/CoX/Utilities/SEGSAdmin/resources.qrc
  Projects/CoX/Utilities/SEGSAdmin/segs.bmp
Labels: review

#403 SEGSAdmin - Bug fix on 'Add User', not asking for access level
  Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.cpp
Labels: review

#381 Fixed "character select list" query.
  Projects/CoX/Data/mysql/segs_game_mysql_create.sql
  Projects/CoX/Data/mysql/segs_mysql_create.sql
  Projects/CoX/Data/pgsql/segs_game_postgres_create.sql
  Projects/CoX/Data/sqlite/segs_game_sqlite_create.sql
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
Labels: bug

#411 Fixed green reticle issue and corrected Target Assist
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/InputState.cpp
  Projects/CoX/Servers/MapServer/Events/InputState.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: bug, review

#421 Compiler warning fixes to address #352
  Projects/CoX/Common/AuthProtocol/AuthLink.cpp
  Projects/CoX/Common/NetStructures/StateInterpolator.cpp
  Projects/CoX/Common/NetStructures/Team.cpp
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/NetCommandManager.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
  Utilities/slav/SLAVLogic.cpp
  Utilities/slav/ServerConnection.cpp
Labels: review

#407 Add player fade in speed to settings.cfg
  Components/Settings.cpp
  Projects/CoX/Data/settings.cfg
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapManager.h
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MapServerData.h
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: in progress

#422 Screen resolution setGeometry warning fix & IPLookup
  Projects/CoX/Utilities/SEGSAdmin/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.h
  Projects/CoX/Utilities/SEGSAdmin/GenerateConfigFileDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/GetIPDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/GetIPDialog.h
  Projects/CoX/Utilities/SEGSAdmin/GetIPDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.h
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.ui
  Projects/CoX/Utilities/SEGSAdmin/icon_lookup.png
  Projects/CoX/Utilities/SEGSAdmin/resources.qrc
Labels: review

#427 Current Logo
  docs/segs-medallion.png
Labels: review

#428 qt5_use_modules was deprecated before Qt 5.10, and removed in Qt 5.11
  Components/CMakeLists.txt
  Projects/CoX/Common/CRUDP_Protocol/CMakeLists.txt
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/NetStructures/CMakeLists.txt
  Projects/CoX/Common/PasswordHasher/CMakeLists.txt
  Projects/CoX/Common/Runtime/CMakeLists.txt
  Projects/CoX/Common/Servers/CMakeLists.txt
  Projects/CoX/Servers/AuthDatabase/CMakeLists.txt
  Projects/CoX/Servers/AuthServer/CMakeLists.txt
  Projects/CoX/Servers/GameDatabase/CMakeLists.txt
  Projects/CoX/Servers/GameServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Utilities/AuthExerciser/CMakeLists.txt
  Projects/CoX/Utilities/BinConverter/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/CMakeLists.txt
  Projects/CoX/Utilities/TextureConverter/CMakeLists.txt
  Projects/CoX/Utilities/dbtool/CMakeLists.txt
  Projects/CoX/Utilities/piggtool/CMakeLists.txt
  Utilities/slav/CMakeLists.txt
Labels: review

#409 Issue #271 - Automatically Updating Characters in Database
  Projects/CoX/Common/GameData/attrib_definitions.h
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Servers/GameDatabase/CMakeLists.txt
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameHandler.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: enhancement

#430 add PUBLIC to target_link_libraries in AuthExerciser
  Projects/CoX/Utilities/AuthExerciser/CMakeLists.txt
Labels: review
