Repository Segs/Segs, pull requests merged in 2018-10, with the labels that each got.

#596 Waypoints implementation with slash command to test `/setwaypoint`
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/Waypoints.h
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, review

#598 Levelup improvements, powers array improvements, queues and timers, and more
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/chardata_definitions.h
  Projects/CoX/Common/GameData/chardata_serializers.cpp
  Projects/CoX/Common/GameData/keybind_definitions.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
  Projects/CoX/Common/NetStructures/CharacterHelpers.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/Browser.h
  Projects/CoX/Servers/MapServer/Events/ClientStates.h
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/Events/InteractWithEntity.h
  Projects/CoX/Servers/MapServer/Events/LevelUp.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/PowerSystemEvents.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: bug, enhancement, review

#595 Exposed contact_dialog methods to Lua
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
Labels: enhancement, lua-related

#604 Testing cache theory on appveyor. Iterated version number
  appveyor.yml
Labels: review

#610 This should fix appveyor, and first-build problems
  Projects/CoX/Common/AuthProtocol/CMakeLists.txt
Labels: review

#614 Let's see if we can get these power updates in.
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: bug, review

#548 Creating a Semi-Standalone EmailHandler that derives from EventProcessor (Part 2)
  Projects/CoX/Common/Servers/HandlerLocator.cpp
  Projects/CoX/Common/Servers/HandlerLocator.h
  Projects/CoX/Data/mysql/segs_game_mysql_create.sql
  Projects/CoX/Data/pgsql/segs_game_postgres_create.sql
  Projects/CoX/Data/sqlite/segs_game_sqlite_create.sql
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.h
  Projects/CoX/Servers/GameServer/CMakeLists.txt
  Projects/CoX/Servers/GameServer/EmailDefinitions.h
  Projects/CoX/Servers/GameServer/EmailEvents.h
  Projects/CoX/Servers/GameServer/EmailHandler.cpp
  Projects/CoX/Servers/GameServer/EmailHandler.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/EmailRead.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, review

#615 Preliminary SeqBits, TriggeredMoves, NetFx. PowerStance. More.
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CoHMath.h
  Projects/CoX/Common/GameData/seq_definitions.h
  Projects/CoX/Common/GameData/seq_serializers.cpp
  Projects/CoX/Common/GameData/seq_serializers.h
  Projects/CoX/Common/NetStructures/CMakeLists.txt
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
  Projects/CoX/Common/NetStructures/CharacterHelpers.h
  Projects/CoX/Common/NetStructures/Costume.cpp
  Projects/CoX/Common/NetStructures/Costume.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Common/NetStructures/Movement.cpp
  Projects/CoX/Common/NetStructures/Movement.h
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Common/NetStructures/StateInterpolator.cpp
  Projects/CoX/Common/NetStructures/StateInterpolator.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/MapXferList.h
  Projects/CoX/Servers/MapServer/Events/SendStance.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, review

#623 Death Dialog works. `/revive` slashcommand. Revive inspirations.
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/ClientStates.h
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
  Projects/CoX/Common/NetStructures/CharacterHelpers.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/DeadNoGurney.h
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/SetClientState.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: enhancement, review

#627 Alternative to Death-By-Zoning
  Projects/CoX/Common/GameData/entitydata_definitions.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug

#611 Added more Lua functions and LogScripts
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.h
  Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement, lua-related

#631 log: Put 'duplicate mod trick' in 'SceneGraph' category
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Data/settings_template.cfg
Labels: enhancement

#630 Adjusted the gui a little
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.ui
Labels: enhancement

#612 SEGSAdmin - Settings & Logging Update
  Components/Settings.cpp
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Utilities/SEGSAdmin/Globals.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.h
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement, review

#638 add docker and Ubuntu 18.04 support; add universal build script
  .gitignore
  Dockerfile
  README.md
  activate.env.template
  docker/scripts/docker-build.sh
  docker/scripts/docker-forward.sh
  docker/scripts/docker-restart.sh
  docker/scripts/docker-start.sh
  docker/scripts/segs
  docker/scripts/segs.sh
Labels: enhancement, sysadmin task

#648 Correct typos in MySQL commands
  Projects/CoX/Data/mysql/segs_game_mysql_create.sql
Labels: bug

#651 The map server was not loading runtime support data.
  Projects/CoX/Servers/MapServer/MapServer.cpp
Labels: review

#653 Fix serialization versioning for client options.
  Components/BitStream.h
  Projects/CoX/Common/CRUDP_Protocol/CMakeLists.txt
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Packet.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Packet.h
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Events.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Events.h
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.cpp
  Projects/CoX/Common/GameData/clientoptions_definitions.h
  Projects/CoX/Common/GameData/clientoptions_serializers.cpp
  Projects/CoX/Common/GameData/playerdata_definitions.h
  Projects/CoX/Common/GameData/playerdata_serializers.cpp
  Projects/CoX/Common/Messages/Map/AddTimeStateLog.h
  Projects/CoX/Common/Messages/Map/ChangeTitle.h
  Projects/CoX/Common/Messages/Map/ChatDividerMoved.cpp
  Projects/CoX/Common/Messages/Map/ContactDialogs.h
  Projects/CoX/Common/Messages/Map/DoorMessage.h
  Projects/CoX/Common/Messages/Map/EmailHeaders.h
  Projects/CoX/Common/Messages/Map/EmailMessageStatus.h
  Projects/CoX/Common/Messages/Map/EmailRead.h
  Projects/CoX/Common/Messages/Map/EntitiesResponse.cpp
  Projects/CoX/Common/Messages/Map/EntitiesResponse.h
  Projects/CoX/Common/Messages/Map/FloatingDamage.h
  Projects/CoX/Common/Messages/Map/FloatingInfo.h
  Projects/CoX/Common/Messages/Map/FriendsListUpdate.h
  Projects/CoX/Common/Messages/Map/GameCommandList.h
  Projects/CoX/Common/Messages/Map/InfoMessageCmd.cpp
  Projects/CoX/Common/Messages/Map/InteractWithEntity.h
  Projects/CoX/Common/Messages/Map/LevelUp.h
  Projects/CoX/Common/Messages/Map/LocationVisited.cpp
  Projects/CoX/Common/Messages/Map/NewEntity.h
  Projects/CoX/Common/Messages/Map/PlaqueVisited.cpp
  Projects/CoX/Common/Messages/Map/SaveClientOptions.cpp
  Projects/CoX/Common/Messages/Map/SendStance.h
  Projects/CoX/Common/Messages/Map/SetClientState.h
  Projects/CoX/Common/Messages/Map/Shortcuts.h
  Projects/CoX/Common/Messages/Map/SidekickOffer.h
  Projects/CoX/Common/Messages/Map/StandardDialogCmd.h
  Projects/CoX/Common/Messages/Map/TeamLooking.h
  Projects/CoX/Common/Messages/Map/TeamOffer.h
  Projects/CoX/Common/Messages/Map/TimeUpdate.h
  Projects/CoX/Common/Messages/Map/TrayAdd.h
  Projects/CoX/Common/Messages/Map/Waypoints.h
  Projects/CoX/Common/Messages/Map/WindowState.cpp
  Projects/CoX/Common/Servers/ServerEndpoint.cpp
  Projects/CoX/Servers/MapServer/EntityStorage.cpp
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
Labels: bug, release blocker, review

#656 hotfix: Close emailhandler on shutdown
  Projects/CoX/Servers/GameServer/GameServer.cpp
Labels: bug

#659 Fix a map entering process to solve link/server blocking.
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.cpp
  Projects/CoX/Common/GameData/Entity.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug, review

#636 Dooranims
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/DeadNoGurney.h
  Projects/CoX/Common/Messages/Map/DoorAnims.h
  Projects/CoX/Common/Messages/Map/FaceLocation.h
  Projects/CoX/Common/Messages/Map/GameCommandList.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/MapEvents.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, review

#643 Add in Contact Lists / Expose Contacts to Lua
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CharacterData.cpp
  Projects/CoX/Common/GameData/CharacterData.h
  Projects/CoX/Common/GameData/Contact.cpp
  Projects/CoX/Common/GameData/Contact.h
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/chardata_serializers.cpp
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/ContactList.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.h
  Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#661 Attempt to fix errors in ScriptEngine.cpp and hotfix for setSpeed
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
Labels: bug, review

#663 Use float duration for reporting keypress times + a few small fixes.
  Projects/CoX/Common/GameData/Movement.cpp
  Projects/CoX/Common/GameData/NpcStore.cpp
  Projects/CoX/Common/GameData/StateInterpolator.cpp
  Projects/CoX/Common/GameData/StateStorage.h
  Projects/CoX/Common/Messages/Map/ContactList.h
  Projects/CoX/Common/Messages/Map/DoorAnims.h
  Projects/CoX/Common/Messages/Map/InputState.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
Labels: hygiene, review

#649 auth: Don't assert on bad reconnection attempts
  Projects/CoX/Common/Messages/Auth/AuthEvents.h
Labels: bug, needs-testing

#664 Temporary workaround for #555 team-removal and side-kick removal
  Projects/CoX/Common/GameData/Team.cpp
  Projects/CoX/Common/GameData/Team.h
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp
  Projects/CoX/Servers/GameServer/EmailService/EmailHandler.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: bug, review

#666 Gcc53 abs fix
  Projects/CoX/Common/GameData/StateInterpolator.cpp
Labels: review

#667 Ubuntu build fixes and ignore Travis macOS builds
  .travis.yml
  Projects/CoX/Common/GameData/power_definitions.h
  Projects/CoX/Common/GameData/seq_definitions.h
  Projects/CoX/Utilities/SEGSAdmin/NetworkManager.h
Labels: bug, review

#665 [skip ci] update docs, version, and readmes
  Projects/CoX/Data/scripts/motd.smlx
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/docs/README.md
  docs/AUTHORS.md
  include/version.h
Labels: hygiene, release blocker, review

#668 A few last-minute fixes
  Projects/CoX/Common/GameData/Powers.cpp
  Projects/CoX/Common/GameData/Team.cpp
  Projects/CoX/Common/Messages/Map/MapXferRequest.h
  Projects/CoX/Servers/GameServer/EmailService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/FriendshipService/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: review

#669 Merge back from master
  README.md
Labels: review
