Repository Segs/Segs, pull requests merged in 2018-04, with the labels that each got.

#294 Set Access Level for new chars to 1, cleaned up some debug output
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Servers/GameServer/GameHandler.cpp
Labels: bug, enhancement

#295 Address Issue #282 in the SlashCommand handlers
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#319 Couple small fixes to m_account_level and Windows serialization
  Projects/CoX/Common/GameData/gui_definitions.h
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Servers/MapServer/MapClient.cpp
Labels: bug

#326 [RFC] Email System
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/EmailHeaders.h
  Projects/CoX/Servers/MapServer/Events/EmailMessageStatus.h
  Projects/CoX/Servers/MapServer/Events/EmailRead.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.h
Labels: enhancement, review

#332 Remove clang as a build target on travis.
  .travis.yml
Labels: review

#339 Do not return a DB error on missing accounts
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/AuthServer/AuthHandler.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
Labels: review

#340 Don't dump the whole vector, dump a single entry, ya dummy
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: review

#343 Fix windows executable and a few db issues
  Projects/CoX/Common/AuthProtocol/AuthLink.cpp
  Projects/CoX/Common/Servers/CMakeLists.txt
  Projects/CoX/Common/Servers/MessageBus.cpp
  Projects/CoX/Common/Servers/MessageBus.h
  Projects/CoX/Common/Servers/ServerEndpoint.cpp
  Projects/CoX/Common/Servers/ServerEndpoint.h
  Projects/CoX/Common/Servers/ServerSupport.cpp
  Projects/CoX/Common/Servers/server_support.h
  Projects/CoX/Servers/AuthServer/AuthServer.cpp
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.cpp
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapManager.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
Labels: review

#345 Add a skeleton of a SceneGraph
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SceneGraph.cpp
  Projects/CoX/Servers/MapServer/SceneGraph.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: review

#347 Squeeze attrib damage and defense definitions
  Projects/CoX/Common/GameData/attrib_definitions.h
  Projects/CoX/Common/GameData/attrib_serializers.cpp
Labels: review

#348 Reduce number of allocations in segsLogMessageOutput
  Projects/CoX/Servers/AuthServer/main.cpp
Labels: review

#349 Mem fixes
  Components/EventProcessor.cpp
  Components/SEGSEvent.cpp
  Components/SEGSEvent.h
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.cpp
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Common/Servers/HandlerLocator.cpp
  Projects/CoX/Common/Servers/MessageBus.cpp
  Projects/CoX/Common/Servers/ServerEndpoint.cpp
  Projects/CoX/Servers/AuthServer/AuthServer.cpp
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/GameServer/GameServer.h
  Projects/CoX/Servers/MapServer/MapManager.cpp
  Projects/CoX/Servers/MapServer/MapManager.h
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MapServer.h
  Projects/CoX/Servers/MapServer/MapTemplate.cpp
  Projects/CoX/Servers/MapServer/MapTemplate.h
Labels: review

#356 Add support for `Interact with this` packets
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/Events/InteractWithEntity.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
Labels: review

#353 Batch of Coverity fixes
  Components/BitStream.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/StateInterpolator.cpp
  Projects/CoX/Common/Servers/ServerEndpoint.h
  Projects/CoX/Servers/GameServer/GameEvents.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/Events/KeybindSettings.cpp
  Projects/CoX/Servers/MapServer/Events/SceneEvent.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Utilities/BinConverter/binConverter.cpp
  Utilities/slav/FileSignatureWorker.cpp
Labels: review

#359 Fix a logic bug when receiving yaw/pitch data from client
  Components/BitStream.h
  Components/SEGSEvent.h
  Components/SEGSTimer.h
  Projects/CoX/Common/AuthProtocol/AuthLink.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/AuthServer/AuthHandler.h
  Projects/CoX/Servers/AuthServer/AuthServer.cpp
  Projects/CoX/Servers/AuthServer/AuthServer.h
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameServer/GameEventFactory.cpp
  Projects/CoX/Servers/GameServer/GameEventFactory.h
  Projects/CoX/Servers/GameServer/GameEvents.cpp
  Projects/CoX/Servers/GameServer/GameEvents.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameHandler.h
  Projects/CoX/Servers/GameServer/GameLink.cpp
  Projects/CoX/Servers/GameServer/GameLink.h
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/GameServer/GameServer.h
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/InputState.cpp
  Projects/CoX/Servers/MapServer/Events/SidekickOffer.h
Labels: review

#364 Fix a crash when a map instance is not located for given map
  Projects/CoX/Servers/MapServer/MapServer.cpp
Labels: review

#365 Doxyfile and default jump height changes
  Doxyfile
  Projects/CoX/Common/NetStructures/Entity.h
Labels: enhancement, review

#366 Update CONTRIBUTING.md [ci skip]
  docs/CONTRIBUTING.md
Labels: review

#378 Remove database schema pngs from codebase
  Projects/CoX/Data/SCHEMA.md
  Projects/CoX/Data/segs_dbschema.png
  Projects/CoX/Data/segs_game_dbschema.png
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
Labels: review

#384 Added new logging categories, cleaned up logging output, and more
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Events.h
  Projects/CoX/Common/GameData/CoHMath.h
  Projects/CoX/Common/GameData/chardata_definitions.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Common/NetStructures/StateInterpolator.cpp
  Projects/CoX/Common/NetStructures/StateInterpolator.h
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Data/settings.cfg
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.h
  Projects/CoX/Servers/MapServer/Events/InputState.cpp
  Projects/CoX/Servers/MapServer/Events/InputState.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/NetCommandManager.cpp
  Projects/CoX/Servers/MapServer/NpcStore.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Utilities/dbtool/main.cpp
Labels: review

#377 Load map scene-graph.
  Projects/CoX/Common/CMakeLists.txt
  Projects/CoX/Common/GameData/CoHMath.h
  Projects/CoX/Common/GameData/gui_definitions.h
  Projects/CoX/Common/GameData/scenegraph_serializers.cpp
  Projects/CoX/Common/GameData/scenegraph_serializers.h
  Projects/CoX/Common/GameData/trick_definitions.h
  Projects/CoX/Common/GameData/trick_serializers.cpp
  Projects/CoX/Common/GameData/trick_serializers.h
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Common/Runtime/CMakeLists.txt
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Common/Runtime/SceneGraph.h
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/EntityStorage.cpp
  Projects/CoX/Servers/MapServer/EntityStorage.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/InputState.cpp
  Projects/CoX/Servers/MapServer/Events/SceneEvent.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.h
  Projects/CoX/Servers/MapServer/MapTemplate.cpp
  Projects/CoX/Servers/MapServer/NetCommandManager.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
  Projects/CoX/Servers/MapServer/NpcGenerator.h
  Projects/CoX/Servers/MapServer/SceneGraph.cpp
  Projects/CoX/Servers/MapServer/SceneGraph.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Utilities/MapViewer/CMakeLists.txt
  Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.cpp
  Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.h
  Projects/CoX/Utilities/MapViewer/src/CohModelConverter.cpp
  Projects/CoX/Utilities/MapViewer/src/CohTextureConverter.h
  Projects/CoX/Utilities/MapViewer/src/MapViewerApp.cpp
  Projects/CoX/Utilities/MapViewer/src/MapViewerApp.h
  Projects/CoX/Utilities/MapViewer/src/SideWindow.cpp
  Projects/CoX/Utilities/MapViewer/src/SideWindow.h
  Projects/CoX/Utilities/MapViewer/src/SideWindow.ui
  Projects/CoX/Utilities/piggtool/main.cpp
Labels: review
