Repository Segs/Segs, pull requests merged in 2018-12, with the labels that each got.

#716 Force logout Working
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/ForceLogout.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/MapEvents.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#717 Added Stores / Store in LuaBot
  Components/Logging.cpp
  Components/Logging.h
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/Store.cpp
  Projects/CoX/Common/GameData/Store.h
  Projects/CoX/Common/GameData/shop_serializers.cpp
  Projects/CoX/Common/GameData/shop_serializers.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/StoresEvents.h
  Projects/CoX/Data/scripts/City_00_01/contacts.lua
  Projects/CoX/Data/scripts/City_00_01/entities.lua
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
  Projects/CoX/Data/scripts/City_01_01/luaBot.lua
  Projects/CoX/Data/scripts/global.lua
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Utilities/BinConverter/binConverter.cpp
Labels: enhancement

#720 Add updateClientContext declaration
  Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
Labels: bug, review

#722 cmake scripts seem to always copy the debug Qt dlls, even for a Release build
  CMakeScripts/Windeployqt.cmake
Labels: bug

#719 Send VisitLocations
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/VisitLocation.cpp
  Projects/CoX/Common/GameData/VisitLocation.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/SendVisitLocation.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#724 Console output/ printf
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/ConsoleMessages.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement
