Repository Segs/Segs, pull requests merged in 2018-09, with the labels that each got.

#531 Dead No Gurney changes.
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/DeadNoGurney.h
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#543 Add friendship service testcase
  Components/BitStream.h
  Components/SEGSEvent.h
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Events.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/StateInterpolator.cpp
  Projects/CoX/Servers/GameServer/FriendshipService/UnitTests/FriendshipServiceFunctions.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
  Utilities/event_gen/CMakeLists.txt
Labels: enhancement, review

#522 Allow Character to AFK and Auto-Logout (Optional)
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/chardata_definitions.h
  Projects/CoX/Common/GameData/chardata_serializers.cpp
  Projects/CoX/Common/GameData/map_definitions.h
  Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
  Projects/CoX/Common/NetStructures/CharacterHelpers.h
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/InputState.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: enhancement, needs-testing

#558 Settings for AFKness
  Components/Settings.cpp
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: enhancement, review

#544 Initial work on map transfers. WIP
  Components/Logging.cpp
  Components/Logging.h
  Projects/CoX/Common/GameData/map_definitions.cpp
  Projects/CoX/Common/GameData/map_definitions.h
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/GameServer/GameEvents.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/MapXferRequest.h
  Projects/CoX/Servers/MapServer/Events/MapXferWait.h
  Projects/CoX/Servers/MapServer/MapClientSession.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MapServer.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, in progress

#559 whoops, renamed variable
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: review

#560 Finalizelevel
  Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: review

#538 Added FaceEntity and FaceLocation events.
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/FaceEntity.h
  Projects/CoX/Servers/MapServer/Events/FaceLocation.h
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, needs-testing

#563 A few fixes and reduce the header includes.
  Components/SEGSEvent.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/Events/GameCommand.h
  Projects/CoX/Servers/MapServer/Events/MapXferList.h
  Projects/CoX/Servers/MapServer/MapClientSession.cpp
  Projects/CoX/Servers/MapServer/MapClientSession.h
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: review

#566 Use 32 bit values for database user_id
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncEvents.h
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Servers/MapServer/Events/FaceEntity.h
  Projects/CoX/Servers/MapServer/Events/FaceLocation.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
Labels: bug, review

#567 Move power tray's serialization version macros to the header.
  Projects/CoX/Common/GameData/trays_serializers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
Labels: bug, regression, review

#540 Gracefully handle more than 5col x 4row of inspirations
  Projects/CoX/Common/GameData/chardata_serializers.cpp
  Projects/CoX/Common/GameData/chardata_serializers.h
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
Labels: hygiene, needs-testing

#570 Missing Bracket in Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
Labels: review

#562 Door Message and test slash command
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/DoorMessage.h
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
Labels: enhancement, review

#573 Starting character infromation read from settings.cfg
  Components/Settings.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Data/settings_template.cfg
Labels: enhancement

#576 Add trade command.
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Common/NetStructures/CMakeLists.txt
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Common/NetStructures/Trade.cpp
  Projects/CoX/Common/NetStructures/Trade.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/TradeCancel.cpp
  Projects/CoX/Servers/MapServer/Events/TradeCancel.h
  Projects/CoX/Servers/MapServer/Events/TradeInit.cpp
  Projects/CoX/Servers/MapServer/Events/TradeInit.h
  Projects/CoX/Servers/MapServer/Events/TradeOffer.cpp
  Projects/CoX/Servers/MapServer/Events/TradeOffer.h
  Projects/CoX/Servers/MapServer/Events/TradeSuccess.cpp
  Projects/CoX/Servers/MapServer/Events/TradeSuccess.h
  Projects/CoX/Servers/MapServer/Events/TradeUpdate.cpp
  Projects/CoX/Servers/MapServer/Events/TradeUpdate.h
  Projects/CoX/Servers/MapServer/Events/TradeWasCancelledMessage.cpp
  Projects/CoX/Servers/MapServer/Events/TradeWasCancelledMessage.h
  Projects/CoX/Servers/MapServer/Events/TradeWasUpdatedMessage.cpp
  Projects/CoX/Servers/MapServer/Events/TradeWasUpdatedMessage.h
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement, review

#578 Fix erroneous inspiration counts and fixed messages when adding…
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: bug, regression, review

#582 Add movement logging for future use in movement branch
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Data/settings_template.cfg
Labels: enhancement, review

#581 AddTimeStateLog and TimeUpdate
  Projects/CoX/Common/NetStructures/Entity.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/AddTimeStateLog.h
  Projects/CoX/Servers/MapServer/Events/GameCommandList.h
  Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
  Projects/CoX/Servers/MapServer/Events/TimeUpdate.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
Labels: enhancement, review

#541 CharacterPower.m_power_tpl is now CharacterPower.get_power_template()
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/chardata_serializers.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, needs-testing, release blocker

#583 Code cleanups and Data Helper organization
  Projects/CoX/Common/GameData/map_definitions.cpp
  Projects/CoX/Common/GameData/map_definitions.h
  Projects/CoX/Common/NetStructures/Friend.cpp
  Projects/CoX/Common/NetStructures/Friend.h
  Projects/CoX/Common/NetStructures/Team.cpp
  Projects/CoX/Common/NetStructures/Team.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/Events/ChatDividerMoved.h
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/Events/FriendsListUpdate.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: hygiene, review

#587 NetStructures no longer uses any of the MapServer internals:
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/keybind_definitions.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Friend.cpp
  Projects/CoX/Common/NetStructures/Friend.h
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Common/NetStructures/Powers.h
  Projects/CoX/Common/NetStructures/Team.cpp
  Projects/CoX/Common/NetStructures/Team.h
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MapServer.h
  Projects/CoX/Servers/MapServer/NpcGenerator.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: review

#590 Use a game data singleton in MapServer instead of it's own instance.
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
Labels: enhancement, review

#588 get maxHP from classes.bin and cleaned up combat level
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/NetStructures/Character.cpp
  Projects/CoX/Common/NetStructures/Character.h
  Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
  Projects/CoX/Common/NetStructures/Powers.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, review
