Repository Segs/Segs, pull requests merged in 2018-08, with the labels that each got.

#496 Allowing DbHandler to get entity data using character name.
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
Labels: enhancement, needs-testing

#503 Use map idx instead of map name to check for a character's map data
  Projects/CoX/Common/GameData/entitydata_definitions.h
  Projects/CoX/Common/GameData/entitydata_serializers.cpp
  Projects/CoX/Common/NetStructures/Friend.cpp
  Projects/CoX/Servers/GameServer/GameEvents.cpp
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#505 Team fix
  Projects/CoX/Common/NetStructures/Entity.cpp
  Projects/CoX/Common/NetStructures/Team.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
Labels: bug, review

#506 Remove `setMapName()` from MapInstance
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug

#508 - Add ability to check for updates on start up utilising the github API
  Projects/CoX/Utilities/SEGSAdmin/AboutDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/AboutDialog.h
  Projects/CoX/Utilities/SEGSAdmin/AboutDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/Globals.cpp
  Projects/CoX/Utilities/SEGSAdmin/Globals.h
  Projects/CoX/Utilities/SEGSAdmin/License.txt
  Projects/CoX/Utilities/SEGSAdmin/NetworkManager.cpp
  Projects/CoX/Utilities/SEGSAdmin/NetworkManager.h
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.h
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.ui
  Projects/CoX/Utilities/SEGSAdmin/SetUpData.ui
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/UpdateDetailDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/UpdateDetailDialog.h
  Projects/CoX/Utilities/SEGSAdmin/UpdateDetailDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/alert-triangle.svg
  Projects/CoX/Utilities/SEGSAdmin/check.svg
  Projects/CoX/Utilities/SEGSAdmin/database.svg
  Projects/CoX/Utilities/SEGSAdmin/download.svg
  Projects/CoX/Utilities/SEGSAdmin/file-plus.svg
  Projects/CoX/Utilities/SEGSAdmin/main.cpp
  Projects/CoX/Utilities/SEGSAdmin/play.svg
  Projects/CoX/Utilities/SEGSAdmin/resources.qrc
  Projects/CoX/Utilities/SEGSAdmin/save.svg
  Projects/CoX/Utilities/SEGSAdmin/segs_splash_1.png
  Projects/CoX/Utilities/SEGSAdmin/settings.svg
  Projects/CoX/Utilities/SEGSAdmin/sliders.svg
  Projects/CoX/Utilities/SEGSAdmin/square.svg
  Projects/CoX/Utilities/SEGSAdmin/users.svg
Labels: review

#512 Add develop branch to Appveyor
  appveyor.yml
Labels: review

#513 Fixed for SEGSAdmin scaling on HDPI displays
  Projects/CoX/Utilities/SEGSAdmin/main.cpp
Labels: enhancement, needs-testing

#500 Improvements to Sync Service
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
Labels: enhancement, needs-testing

#534 Updating chardata to mediumblob
  Projects/CoX/Data/mysql/segs_game_mysql_create.sql
Labels: bug, review

#536 Updated appveyor disabling win 32 build
  appveyor.yml
Labels: review
