Repository Segs/Segs, pull requests merged in 2019-02, with the labels that each got.

#745 Extend AdminRPC server and update settings_template.cfg
  .gitignore
  Components/Logging.cpp
  Components/Logging.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/AuthServer/AdminRPC.h
Labels: enhancement

#765 Stop excessive blank lines in SEGSAdmin output
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
Labels: review

#750 Lua Hide and Seek mission
  Components/CMakeLists.txt
  Components/TimeHelpers.cpp
  Components/TimeHelpers.h
  Projects/CoX/CMakeLists.txt
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CharacterData.cpp
  Projects/CoX/Common/GameData/CharacterData.h
  Projects/CoX/Common/GameData/CharacterStatistics.cpp
  Projects/CoX/Common/GameData/CharacterStatistics.h
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
  Projects/CoX/Data/scripts/City_01_01/contacts.lua
  Projects/CoX/Data/scripts/City_01_01/hideAndSeek.lua
  Projects/CoX/Data/scripts/City_01_01/luaBot.lua
  Projects/CoX/Data/scripts/global.lua
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
  Projects/CoX/Servers/MapServer/MessageHelpers.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.h
  Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, lua-related

#759 AdminRPC: change getVersion output and add getCodename
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/AuthServer/AdminRPC.h
Labels: enhancement, review

#766 Character creation bug fix and "EMPTY" string tidy
  Projects/CoX/Common/GameData/Character.cpp
  Projects/CoX/Common/Messages/Game/GameEvents.cpp
  Projects/CoX/Common/Messages/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
Labels: bug, review

#767 Implement official server map indexes.
  Projects/CoX/Common/GameData/entitydata_definitions.h
  Projects/CoX/Common/GameData/map_definitions.cpp
  Projects/CoX/Common/GameData/map_definitions.h
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MapServer.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement

#771 Split log category's into individual files
  CMakeLists.txt
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.h
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement, review

#754 Event for map swap collisions. Trigger map swap on collision.
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/map_definitions.cpp
  Projects/CoX/Common/GameData/map_definitions.h
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.h
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Servers/MapServer/MapServer.h
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: enhancement, review

#773 mysql: Interim reconnection fix
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
Labels: bug, review

#770 Lua Relay Race / Mission Objective Timer
  Projects/CoX/CMakeLists.txt
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CharacterData.cpp
  Projects/CoX/Common/GameData/CharacterData.h
  Projects/CoX/Common/GameData/CharacterStatistics.cpp
  Projects/CoX/Common/GameData/CharacterStatistics.h
  Projects/CoX/Common/GameData/Clue.cpp
  Projects/CoX/Common/GameData/Clue.h
  Projects/CoX/Common/GameData/Contact.cpp
  Projects/CoX/Common/GameData/Contact.h
  Projects/CoX/Common/GameData/PlayerStatistics.cpp
  Projects/CoX/Common/GameData/PlayerStatistics.h
  Projects/CoX/Common/GameData/Task.h
  Projects/CoX/Common/GameData/playerdata_definitions.h
  Projects/CoX/Common/GameData/playerdata_serializers.cpp
  Projects/CoX/Common/Messages/Map/ContactList.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/Tasks.h
  Projects/CoX/Data/scripts/City_01_01/contacts.lua
  Projects/CoX/Data/scripts/City_01_01/hideAndSeek.lua
  Projects/CoX/Data/scripts/City_01_01/locations.lua
  Projects/CoX/Data/scripts/City_01_01/relayRace.lua
  Projects/CoX/Data/scripts/global.lua
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, lua-related, review

#777 logging: Name logs with ISO-8601 compliant dates
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
Labels: bug, needs-testing, review

#784 Commented out unused parameters
  Projects/CoX/Common/GameData/power_serializers.cpp
  Projects/CoX/Common/Messages/Map/ForceLogout.h
  Projects/CoX/Common/Messages/Map/LevelUp.h
  Projects/CoX/Common/Messages/Map/Tasks.h
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Utilities/AuthExerciser/DummyClass.cpp
Labels: hygiene

#763 Email regression fix
  Components/TimeHelpers.cpp
  Projects/CoX/Common/Messages/Map/EmailHeaders.h
  Projects/CoX/Servers/GameServer/EmailService/EmailHandler.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug, regression, release blocker, review

#781 Server side encounter spawning / WIP
  Components/Logging.cpp
  Components/Logging.h
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/GameData/EntityHelpers.h
  Projects/CoX/Common/GameData/spawn_definitions.cpp
  Projects/CoX/Common/GameData/spawn_definitions.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/CritterGenerator.cpp
  Projects/CoX/Servers/MapServer/CritterGenerator.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityStorage.cpp
  Projects/CoX/Servers/MapServer/EntityStorage.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
Labels: enhancement, review

#787 Create Settings.cfg version and centralize version locations
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.h
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.h
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
  Projects/CoX/Utilities/SEGSAdmin/main.cpp
  include/Version.h
Labels: enhancement, review

#786 rpc: Add WebUI statistics procedure
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/AuthServer/AdminRPC.h
Labels: enhancement, review, rpc-related

#790 Fix for GCC / Linux build
  Utilities/event_gen/main.cpp
Labels: bug, review

#783 addUser RPC Service and RPCTestClient
  CMakeLists.txt
  Projects/CoX/Common/Messages/AuthDatabase/AuthDBSyncEvents.h
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp
  Projects/CoX/Servers/AuthDatabase/UnitTests/AuthDBEventRegistry.cpp
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/AuthServer/AdminRPC.h
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/AuthServer/AuthHandler.h
  Projects/CoX/Utilities/CMakeLists.txt
  Projects/CoX/Utilities/RPCTestClient/CMakeLists.txt
  Projects/CoX/Utilities/RPCTestClient/RPCTestClient.cpp
  Projects/CoX/Utilities/RPCTestClient/RPCTestClient.h
  Projects/CoX/Utilities/RPCTestClient/RPCTestClient.ui
  Projects/CoX/Utilities/RPCTestClient/main.cpp
  Utilities/event_gen/main.cpp
Labels: enhancement, review, rpc-related

#788 Character constructor issue
  Components/Logging.cpp
  Components/Logging.h
  Projects/CoX/Common/GameData/Character.cpp
  Projects/CoX/Common/Messages/Game/GameEvents.cpp
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug, review
