Repository Segs/Segs, pull requests merged in 2019-03, with the labels that each got.

#795 Update jcon files to upstream joncol/jcon-cpp@97790509ca
  3rd_party/jcon-cpp/README.md
  3rd_party/jcon-cpp/src/jcon/json_rpc_client.cpp
  3rd_party/jcon-cpp/src/jcon/json_rpc_server.cpp
  3rd_party/jcon-cpp/src/jcon/json_rpc_server.h
  3rd_party/jcon-cpp/src/jcon/json_rpc_tcp_server.cpp
  3rd_party/jcon-cpp/src/jcon/json_rpc_tcp_server.h
  3rd_party/jcon-cpp/src/jcon/json_rpc_websocket_server.cpp
  3rd_party/jcon-cpp/src/jcon/json_rpc_websocket_server.h
Labels: review

#796 rpc: Build jcon-cpp with -DNDEBUG
  3rd_party/jcon-cpp/src/jcon/CMakeLists.txt
  3rd_party/jcon-cpp/src/jcon/json_rpc_endpoint.cpp
Labels: review

#798 Updating version for -dev build
  CMakeLists.txt
  Projects/CoX/Common/GameData/Task.cpp
  Projects/CoX/Common/GameData/VisitLocation.cpp
  Projects/CoX/Common/GameData/shop_serializers.cpp
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
  include/Version.h
Labels: hygiene, review

#806 Add XP Multiplier to SEGSAdmin
  Components/Settings.cpp
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.h
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement, review

#810 Added instructions for manually adding auth registry key if Cox-Auth doesn't work
  Projects/CoX/docs/README.md
  docs/COH-CLIENT_INSTALL-WINDOWS.md
Labels: review

#809 QoL adjustments
  Projects/CoX/Common/GameData/Movement.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.ui
Labels: bug, review

#812 Fix funky layout after Doxy generation [skip ci]
  Doxyfile
Labels: bug, review

#815 Update version and add logging [skip ci]
  Doxyfile
Labels: enhancement

#816 Add Doxygen main page [skip ci]
  Doxyfile
  docs/doxy_index.md
Labels: enhancement, review

#688 Power changes to toggles and buffs
  Projects/CoX/Common/GameData/Character.cpp
  Projects/CoX/Common/GameData/Character.h
  Projects/CoX/Common/GameData/CharacterHelpers.cpp
  Projects/CoX/Common/GameData/CharacterHelpers.h
  Projects/CoX/Common/GameData/Entity.cpp
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/GameData/EntityHelpers.h
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/Powers.cpp
  Projects/CoX/Common/GameData/Powers.h
  Projects/CoX/Common/GameData/power_definitions.h
  Projects/CoX/Common/GameData/power_serializers.cpp
  Projects/CoX/Common/GameData/power_serializers.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: bug, enhancement, review

#818 Persistent revealed fog of war
  Components/serialization_types.h
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/PlayerProgress.cpp
  Projects/CoX/Common/GameData/PlayerProgress.h
  Projects/CoX/Common/GameData/playerdata_definitions.h
  Projects/CoX/Common/GameData/playerdata_serializers.cpp
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/GameCommandList.h
  Projects/CoX/Common/Messages/Map/MapEventTypes.h
  Projects/CoX/Common/Messages/Map/VisitMapCells.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: enhancement, review

#823 Adjusted surface params
  Projects/CoX/Common/GameData/Movement.cpp
Labels: enhancement, review
