Repository Segs/Segs, pull requests merged in 2019-01, with the labels that each got.

#718 Readme: Updated install instructions
  README.md
  docs/COMPILE_AND_INSTALL_CENTOS.md
  docs/COMPILE_AND_INSTALL_FEDORA.md
  docs/COMPILE_AND_INSTALL_FREEBSD.md
  docs/COMPILE_AND_INSTALL_UBUNTU.md
  docs/COMPILE_AND_INSTALL_WINDOWS.md
  docs/DOCKER.md
Labels: non-programmer

#730 Updated travis badge to new dot com address [skip ci]
  README.md
Labels: non-programmer, review

#733 Readme: Add Multiverse Repo CLI and some better instructions
  docs/COMPILE_AND_INSTALL_UBUNTU.md
Labels: non-programmer

#725 Code cleanups and attempted build fix
  3rd_party/glm/simd/platform.h
  Projects/CoX/Common/GameData/VisitLocation.cpp
Labels: bug, review

#739 A few cleanups
  Components/Settings.cpp
  Projects/CoX/Common/GameData/Store.cpp
  Projects/CoX/Common/GameData/entitydata_definitions.h
  Projects/CoX/Servers/AuthServer/AdminRPC.h
  Projects/CoX/Servers/GameServer/GameServer.cpp
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
Labels: hygiene, review

#737 [skip ci] Readme: add client install, segsadmin config and some notes
  README.md
  docs/COH-CLIENT_INSTALL-UBUNTU.md
  docs/COH-CLIENT_INSTALL-WINDOWS.md
  docs/CONTRIBUTING.md
  docs/SEGS-COMPILE_AND_INSTALL-CENTOS.md
  docs/SEGS-COMPILE_AND_INSTALL-DOCKER.md
  docs/SEGS-COMPILE_AND_INSTALL-FEDORA.md
  docs/SEGS-COMPILE_AND_INSTALL-FREEBSD.md
  docs/SEGS-COMPILE_AND_INSTALL-UBUNTU.md
  docs/SEGS-COMPILE_AND_INSTALL-WINDOWS.md
  docs/SEGS-CONFIGURE_WITH_SEGSADMIN.md
Labels: non-programmer

#740 Add `ent_types` conversion feature to binConverter.
  Components/serialization_types.h
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/seq_definitions.cpp
  Projects/CoX/Common/GameData/seq_definitions.h
  Projects/CoX/Common/GameData/seq_serializers.cpp
  Projects/CoX/Common/GameData/seq_serializers.h
  Projects/CoX/Common/Messages/Map/ContactList.h
  Projects/CoX/Utilities/BinConverter/binConverter.cpp
Labels: review
