Repository Segs/Segs, pull requests merged in 2019-04, with the labels that each got.

#764 Refactoring MapInstance into multiple Services
  Projects/CoX/Common/Servers/InternalEvents.h
  Projects/CoX/Servers/GameServer/CMakeLists.txt
  Projects/CoX/Servers/GameServer/CharacterService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/CharacterService/CharacterService.cpp
  Projects/CoX/Servers/GameServer/CharacterService/CharacterService.h
  Projects/CoX/Servers/GameServer/CharacterService/EnhancementService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/CharacterService/EnhancementService/EnhancementService.cpp
  Projects/CoX/Servers/GameServer/CharacterService/EnhancementService/EnhancementService.h
  Projects/CoX/Servers/GameServer/CharacterService/InspirationService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/CharacterService/InspirationService/InspirationService.cpp
  Projects/CoX/Servers/GameServer/CharacterService/InspirationService/InspirationService.h
  Projects/CoX/Servers/GameServer/CharacterService/PowerService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/CharacterService/PowerService/PowerService.cpp
  Projects/CoX/Servers/GameServer/CharacterService/PowerService/PowerService.h
  Projects/CoX/Servers/GameServer/ChatService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/ChatService/ChatService.cpp
  Projects/CoX/Servers/GameServer/ChatService/ChatService.h
  Projects/CoX/Servers/GameServer/ClientOptionService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/ClientOptionService/ClientOptionService.cpp
  Projects/CoX/Servers/GameServer/ClientOptionService/ClientOptionService.h
  Projects/CoX/Servers/GameServer/EmailService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/EmailService/EmailService.cpp
  Projects/CoX/Servers/GameServer/EmailService/EmailService.h
  Projects/CoX/Servers/GameServer/InteractionService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/InteractionService/InteractionService.cpp
  Projects/CoX/Servers/GameServer/InteractionService/InteractionService.h
  Projects/CoX/Servers/GameServer/LocationService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/LocationService/LocationService.cpp
  Projects/CoX/Servers/GameServer/LocationService/LocationService.h
  Projects/CoX/Servers/GameServer/TradingService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/TradingService/TradingService.cpp
  Projects/CoX/Servers/GameServer/TradingService/TradingService.h
  Projects/CoX/Servers/GameServer/ZoneTransferService/CMakeLists.txt
  Projects/CoX/Servers/GameServer/ZoneTransferService/ZoneTransferService.cpp
  Projects/CoX/Servers/GameServer/ZoneTransferService/ZoneTransferService.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
Labels: enhancement, hygiene, review

#793 Scripting engine refactor
  Components/Logging.cpp
  Projects/CoX/Common/GameData/spawn_definitions.cpp
  Projects/CoX/Common/GameData/spawn_definitions.h
  Projects/CoX/Common/Messages/Map/StoresEvents.h
  Projects/CoX/Servers/MapServer/CMakeLists.txt
  Projects/CoX/Servers/MapServer/CritterGenerator.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/CMakeLists.txt
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine.h
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEnginePrivate.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEnginePrivate.h
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_CharacterTypes.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_GenericTypes.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_Helpers.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_Null.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_SpawnerTypes.cpp
Labels: hygiene, review

#826 Resolve issue causing out of bounds error when accessing m_visible_map_cells.
  Components/serialization_types.h
  Projects/CoX/Common/GameData/PlayerProgress.h
  Projects/CoX/Common/Messages/Map/VisitMapCells.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: bug, review

#836 Update WhoAll
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: bug, review

#840 Fix PostgreSQL scripts [skip ci]
  Projects/CoX/Data/pgsql/segs_game_postgres_create.sql
  Projects/CoX/Data/pgsql/segs_postgres_create.sql
Labels: bug, review

#842 Alleviate some build warnings
  Projects/CoX/Common/GameData/particlesys_serializers.cpp
  Projects/CoX/Common/Messages/Map/VisitMapCells.h
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/MapServer/CritterGenerator.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: hygiene, review

#843 Small bug fixes for MOTD and AutoAFK. Added logAFK
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Common/GameData/CharacterHelpers.cpp
  Projects/CoX/Common/GameData/CharacterHelpers.h
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/GameData/Movement.cpp
  Projects/CoX/Common/Messages/Map/InputState.cpp
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
Labels: bug, review

#847 Fix for debug logs not showing with new settings.cfg
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
Labels: bug, review

#845 Adjusted server calls to lua dialog button callbacks / Adjusted random enhancement level
  Projects/CoX/Common/GameData/Character.h
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Data/scripts/City_00_01/luaBot.lua
  Projects/CoX/Data/scripts/City_01_01/luaBot.lua
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_CharacterTypes.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: bug, lua-related, review

#848 Fix to issues in current Map Instance refactor
  Projects/CoX/Servers/GameServer/ZoneTransferService/ZoneTransferService.cpp
Labels: bug, review

#852 Class Index lookups fix
  Projects/CoX/Common/GameData/GameDataStore.cpp
Labels: bug, review

#854 Simplify byte_sum adjustment in VisitMapCells.h
  Projects/CoX/Common/Messages/Map/VisitMapCells.h
Labels: hygiene, review

#855 Reaped Link Logging
  Components/Logging.cpp
  Components/Logging.h
  Components/Settings.cpp
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Data/settings_template.cfg
Labels: enhancement, review

#839 Build Output Folder reorganization
  3rd_party/CMakeLists.txt
  CMakeLists.txt
  CMakeScripts/Macdeployqt.cmake
  Components/Settings.cpp
  Components/Settings.h
  Projects/CMakeLists.txt
  Projects/CoX/CMakeLists.txt
  Projects/CoX/Clients/Client/CMakeLists.txt
  Projects/CoX/Common/AuthProtocol/UnitTests/CMakeLists.txt
  Projects/CoX/Common/CRUDP_Protocol/UnitTests/CMakeLists.txt
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/bodypart_serializers.cpp
  Projects/CoX/Common/GameData/origin_definitions.h
  Projects/CoX/Common/GameData/other_definitions.h
  Projects/CoX/Common/GameData/shop_serializers.cpp
  Projects/CoX/Common/GameData/shop_serializers.h
  Projects/CoX/Common/Messages/Map/GameCommand.h
  Projects/CoX/Common/Messages/Map/VisitMapCells.h
  Projects/CoX/Data/mysql/segs_mysql_create.sql
  Projects/CoX/Data/pgsql/segs_postgres_create.sql
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Data/sqlite/segs_sqlite_create.sql
  Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
  Projects/CoX/Servers/AuthDatabase/UnitTests/CMakeLists.txt
  Projects/CoX/Servers/AuthServer/CMakeLists.txt
  Projects/CoX/Servers/AuthServer/main.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/UnitTests/CMakeLists.txt
  Projects/CoX/Servers/GameServer/FriendshipService/UnitTests/CMakeLists.txt
  Projects/CoX/Servers/GameServer/UnitTests/CMakeLists.txt
  Projects/CoX/Servers/MapServer/UnitTests/CMakeLists.txt
  Projects/CoX/Utilities/AuthExerciser/CMakeLists.txt
  Projects/CoX/Utilities/BinConverter/CMakeLists.txt
  Projects/CoX/Utilities/MapViewer/CMakeLists.txt
  Projects/CoX/Utilities/RPCTestClient/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/Globals.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/TextureConverter/CMakeLists.txt
  Projects/CoX/Utilities/dbtool/CMakeLists.txt
  Projects/CoX/Utilities/dbtool/main.cpp
  Projects/CoX/Utilities/piggtool/CMakeLists.txt
  Utilities/event_gen/CMakeLists.txt
  Utilities/slav/CMakeLists.txt
Labels: enhancement, hygiene, needs testing, review

#857 Proposed fix for settings file creation and other db drivers
  Components/Logging.cpp
  Components/Settings.cpp
  Components/Settings.h
  Projects/CoX/Servers/AuthServer/AuthServer.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Utilities/dbtool/main.cpp
Labels: bug, release blocker, review

#859 Adjust stale link ACE_Time values
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: hygiene, review

#860 Categorize the "Sending new Powerstance" message [skip ci]
  Projects/CoX/Common/AuthProtocol/AuthLink.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
Labels: hygiene, review

#865 Refinement to powers
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/GameData/Powers.h
  Projects/CoX/Common/GameData/power_serializers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: enhancement, review

#867 Add password confirmation to add user flows in SEGSAdmin
  Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.ui
Labels: enhancement, review

#868 Update SEGS admin doc link
  docs/SEGS-COMPILE_AND_INSTALL-WINDOWS.md
Labels: non-programmer

#873 Adds option for ticks per second
  Projects/CoX/Common/GameData/Entity.cpp
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Data/settings_template.cfg
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Labels: enhancement

#877 Fix bug of tells to unfound targets causing crash
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: review

#878 [ci-skip] Fix various warnings.
  Components/BitStream.h
  Projects/CoX/Common/GameData/Character.cpp
  Projects/CoX/Common/GameData/Clue.h
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/GameDataStore.h
  Projects/CoX/Common/GameData/Movement.cpp
  Projects/CoX/Common/GameData/Movement.h
  Projects/CoX/Common/GameData/Powers.cpp
  Projects/CoX/Common/GameData/StateInterpolator.cpp
  Projects/CoX/Common/GameData/StateStorage.cpp
  Projects/CoX/Common/GameData/keybind_serializers.cpp
  Projects/CoX/Common/Messages/Map/ClueList.h
  Projects/CoX/Common/Messages/Map/InputState.cpp
  Projects/CoX/Common/Messages/Map/StoresEvents.h
  Projects/CoX/Common/Messages/Map/Tasks.h
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/MessageHelpers.h
  Projects/CoX/Utilities/AuthExerciser/main.cpp
  Projects/CoX/Utilities/MapViewer/src/CoHModelLoader.cpp
  Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.cpp
  Projects/CoX/Utilities/MapViewer/src/MapViewerApp.cpp
  Projects/CoX/Utilities/dbtool/main.cpp
Labels: review

#879 A few small fixes to problems detected by Address/UB sanitizers.
  Components/Buffer.h
  Projects/CoX/Common/GameData/Friend.cpp
  Projects/CoX/Common/GameData/Friend.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
Labels: review

#869 Delayed/repeat power effects
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/GameData/Powers.h
  Projects/CoX/Common/Messages/Map/MapEvents.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.h
Labels: enhancement, review

#880 Removed a few small threading issues
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.h
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.cpp
  Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.h
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
Labels: review

#853 [WIP] Timer interface refactor
  CMakeLists.txt
  Components/EventProcessor.cpp
  Components/EventProcessor.h
  Components/SEGSEvent.h
  Components/SEGSTimer.cpp
  Components/SEGSTimer.h
  Components/TimeEvent.h
  Projects/CoX/Common/GameData/CharacterHelpers.cpp
  Projects/CoX/Common/GameData/CharacterHelpers.h
  Projects/CoX/Common/Servers/ClientManager.h
  Projects/CoX/Common/Servers/MessageBus.cpp
  Projects/CoX/Common/Servers/MessageBus.h
  Projects/CoX/Servers/AuthServer/AuthHandler.cpp
  Projects/CoX/Servers/AuthServer/AuthHandler.h
  Projects/CoX/Servers/GameServer/GameHandler.cpp
  Projects/CoX/Servers/GameServer/GameHandler.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapClientSession.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MapInstance.h
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_GenericTypes.cpp
Labels: enhancement, review

#882 Slash command refactor
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
Labels: enhancement, hygiene
