Repository Segs/Segs, pull requests merged in 2019-05, with the labels that each got.

#884 v0.7.0 Release Candidate 1
  Projects/CoX/Data/scripts/City_00_01/entities.lua
  Projects/CoX/Data/scripts/City_01_01/entities.lua
  Projects/CoX/Data/scripts/City_01_02/entities.lua
  Projects/CoX/Data/scripts/City_02_01/entities.lua
  Projects/CoX/Data/scripts/City_02_02/entities.lua
  Projects/CoX/Data/scripts/City_03_01/entities.lua
  Projects/CoX/Data/scripts/City_03_02/entities.lua
  Projects/CoX/Data/scripts/Hazard_01_01/entities.lua
  Projects/CoX/Data/scripts/Hazard_02_01/entities.lua
  Projects/CoX/Data/scripts/Hazard_03_01/entities.lua
  Projects/CoX/Data/scripts/motd.smlx
  Projects/CoX/Data/scripts/spawners.lua
  Projects/CoX/Servers/AuthServer/AdminRPC.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  docs/AUTHORS.md
  include/Version.h
Labels: enhancement, review

#885 Added powers.json to readme
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Data/scripts/motd.smlx
  docs/SEGS-COMPILE_AND_INSTALL-UBUNTU.md
  docs/SEGS-CONFIGURE_WITH_SEGSADMIN.md
Labels: documentation, non-programmer, review

#887 world_update_ticks_per_sec hotfix
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
  include/Version.h
Labels: bug, release blocker, review

#889 Teleport slash cmd, fix for multiple target names, adjust access lvls
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/SlashCommand.h
Labels: bug, enhancement, review

#890 added cmake option to enable/disable building client patch
  CMakeLists.txt
  Projects/CoX/Clients/CMakeLists.txt
Labels: enhancement

#894 [ci skip] Dbtool hotfix
  Projects/CoX/Data/mysql/segs_game_mysql_create.sql
  Projects/CoX/Data/pgsql/segs_game_pgsql_create.sql
  Projects/CoX/Data/sqlite/segs_game_sqlite_create.sql
  Projects/CoX/Utilities/dbtool/DatabaseConfig.cpp
Labels: bug, review

#896 Fix for windows sqlite database removal issues
  Projects/CoX/Utilities/dbtool/DBConnection_Create.cpp
Labels: bug, review
