Repository Segs/Segs, pull requests merged in 2020-09, with the labels that each got.

#933 Removed references to forums in docs
  Projects/CoX/docs/README.md
  docs/CONTRIBUTING.md
  docs/SEGS-COMPILE_AND_INSTALL-CENTOS.md
  docs/SEGS-COMPILE_AND_INSTALL-FEDORA.md
  docs/SEGS-COMPILE_AND_INSTALL-FREEBSD.md
  docs/doxy_index.md
Labels: documentation

#934 Legal
  Projects/CoX/docs/Legal.txt
  docs/Legal.txt
Labels: documentation

#817 [WIP] Initial AI combat response
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: enhancement, review

#925 Entity Update Flags
  Projects/CoX/Common/GameData/CharacterHelpers.cpp
  Projects/CoX/Common/GameData/Entity.cpp
  Projects/CoX/Common/GameData/Entity.h
  Projects/CoX/Common/GameData/EntityHelpers.cpp
  Projects/CoX/Common/GameData/EntityHelpers.h
  Projects/CoX/Common/GameData/Movement.cpp
  Projects/CoX/Common/GameData/keybind_definitions.h
  Projects/CoX/Common/Messages/EmailService/EmailEvents.h
  Projects/CoX/Common/Messages/GameDatabase/GameDBSyncEvents.h
  Projects/CoX/Common/Messages/Map/AddTimeStateLog.h
  Projects/CoX/Common/Messages/Map/Browser.h
  Projects/CoX/Common/Messages/Map/CMakeLists.txt
  Projects/CoX/Common/Messages/Map/ChangeTitle.h
  Projects/CoX/Common/Messages/Map/ChatMessage.h
  Projects/CoX/Common/Messages/Map/ConsoleMessages.h
  Projects/CoX/Common/Messages/Map/DeadNoGurney.h
  Projects/CoX/Common/Messages/Map/EntitiesResponse.cpp
  Projects/CoX/Common/Messages/Map/EntitiesResponse.h
  Projects/CoX/Common/Messages/Map/FaceEntity.h
  Projects/CoX/Common/Messages/Map/FaceLocation.h
  Projects/CoX/Common/Messages/Map/FloatingDamage.h
  Projects/CoX/Common/Messages/Map/GameCommandList.h
  Projects/CoX/Common/Messages/Map/InfoMessageCmd.h
  Projects/CoX/Common/Messages/Map/MapEvents.h
  Projects/CoX/Common/Messages/Map/MessageChannels.h
  Projects/CoX/Common/Messages/Map/StoresEvents.h
  Projects/CoX/Common/Messages/Map/TradeCancel.h
  Projects/CoX/Common/Messages/Map/TradeInit.h
  Projects/CoX/Common/Messages/Map/TradeOffer.h
  Projects/CoX/Common/Messages/Map/TradeSuccess.h
  Projects/CoX/Common/Messages/Map/TradeUpdate.h
  Projects/CoX/Common/Messages/Map/VisitMapCells.h
  Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
  Projects/CoX/Servers/GameDatabase/GameDBSyncService.cpp
  Projects/CoX/Servers/GameServer/EmailService/EmailHandler.h
  Projects/CoX/Servers/GameServer/FriendshipService/UnitTests/FriendshipEventRegistry.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.cpp
  Projects/CoX/Servers/MapServer/DataHelpers.h
  Projects/CoX/Servers/MapServer/EntityStorage.cpp
  Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
  Projects/CoX/Servers/MapServer/MapEventFactory.cpp
  Projects/CoX/Servers/MapServer/MapInstance.cpp
  Projects/CoX/Servers/MapServer/MessageHelpers.cpp
  Projects/CoX/Servers/MapServer/ScriptingEngine/ScriptingEngine_GenericTypes.cpp
  Projects/CoX/Servers/MapServer/SlashCommands/SlashCommand.cpp
  Projects/CoX/Servers/MapServer/SlashCommands/SlashCommand_Debug.cpp
  Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Labels: enhancement
