Repository Segs/Segs, pull requests merged in 2020-03, with the labels that each got.

#910 Add discord badge to readme
  README.md
Labels: documentation

#915 Updated Documentation to clean up old information
  docs/AUTHORS.md
  docs/COH-CLIENT_INSTALL-UBUNTU.md
  docs/COH-CLIENT_INSTALL-WINDOWS.md
  docs/CONTRIBUTING.md
  docs/SEGS-COMPILE_AND_INSTALL-WINDOWS.md
  docs/SEGS-CONFIGURE_WITH_SEGSADMIN.md
  docs/doxy_index.md
  docs/man/AuthExerciser.1
  docs/man/authserver.1
  docs/man/dbtool.1
  docs/man/piggtool.1
Labels: documentation

#917 Scene importer
  3rd_party/naked_ace.tgz
  3rd_party/prebuilt/.gitignore
  3rd_party/prebuilt/.placeholder
  CMakeLists.txt
  CMakeScripts/SDKHelper.cmake
  Components/CMakeLists.txt
  Components/serialization_common.cpp
  Components/serialization_common.h
  Projects/CoX/Common/GameData/CMakeLists.txt
  Projects/CoX/Common/GameData/CharacterAttributes.cpp
  Projects/CoX/Common/GameData/DataStorage.cpp
  Projects/CoX/Common/GameData/DataStorage.h
  Projects/CoX/Common/GameData/GameDataStore.cpp
  Projects/CoX/Common/GameData/fx_serializers.cpp
  Projects/CoX/Common/GameData/power_serializers.cpp
  Projects/CoX/Common/GameData/scenegraph_serializers.cpp
  Projects/CoX/Common/GameData/scenegraph_serializers.h
  Projects/CoX/Common/GameData/trick_serializers.cpp
  Projects/CoX/Common/Runtime/Animation.cpp
  Projects/CoX/Common/Runtime/Animation.h
  Projects/CoX/Common/Runtime/Model.cpp
  Projects/CoX/Common/Runtime/Model.h
  Projects/CoX/Common/Runtime/Prefab.cpp
  Projects/CoX/Common/Runtime/Prefab.h
  Projects/CoX/Common/Runtime/RuntimeData.cpp
  Projects/CoX/Common/Runtime/RuntimeData.h
  Projects/CoX/Common/Runtime/SceneGraph.cpp
  Projects/CoX/Common/Runtime/SceneGraph.h
  Projects/CoX/Common/Runtime/Sequencer.cpp
  Projects/CoX/Common/Runtime/Sequencer.h
  Projects/CoX/Editor/CMakeLists.txt
  Projects/CoX/Editor/main.cpp
  Projects/CoX/Editor/plugins/CMakeLists.txt
  Projects/CoX/Editor/plugins/formats/CMakeLists.txt
  Projects/CoX/Editor/plugins/formats/scene/CMakeLists.txt
  Projects/CoX/Editor/plugins/formats/scene/LoadingContext.h
  Projects/CoX/Editor/plugins/formats/scene/resource_importer_geo.cpp
  Projects/CoX/Editor/plugins/formats/scene/resource_importer_geo.h
  Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
  Projects/CoX/Servers/MapServer/MapServer.cpp
  Projects/CoX/Utilities/BinConverter/binConverter.cpp
  Utilities/event_gen/main.cpp
Labels: enhancement

#918 [WIP] ACE dll build fix & SEGSAdmin BinConverter Addition
  3rd_party/CMakeLists.txt
  3rd_party/ExternalProject_ACE.cmake
  3rd_party/naked_ace.tgz
  Projects/CoX/Utilities/SEGSAdmin/CMakeLists.txt
  Projects/CoX/Utilities/SEGSAdmin/Helpers.cpp
  Projects/CoX/Utilities/SEGSAdmin/Helpers.h
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
  Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.h
  Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp
  Projects/CoX/Utilities/SEGSAdmin/SetUpData.h
  Projects/CoX/Utilities/SEGSAdmin/Worker.cpp
  Projects/CoX/Utilities/SEGSAdmin/Worker.h
Labels: bug, enhancement

#922 SEGSAdmin fix for BinConverter on Linux/MacOS
  Projects/CoX/Utilities/SEGSAdmin/Worker.cpp
Labels: bug
